networks:
  default:
    driver: bridge

services:
  webserver:
    networks:
      - default
      - app-network
    environment:
      - StarTrekWeatherApi__BaseUrl=http://weather-api:8080
      - StarTrekWeatherApi__Username=admin
      - StarTrekWeatherApi__Password=password123
